#define Job types
JOB_TYPE_DF_PRE_PROCESS = '1'
JOB_TYPE_CNN_TRAIN = '2'
JOB_TYPE_CSV_UPLOAD = '3'
JOB_TYPE_EVAL_MODEL = '4'
JOB_TYPE_CNN_SEARCH_DATA = '5'

#define Store types
DATA_STORE_TYPE_HBASE = '1'
DATA_STORE_TYPE_IMAGE = '2'
DATA_STORE_TYPE_S3 = '3'
DATA_STORE_TYPE_LOCAL = '4'
