# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-09 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NNList',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True)),
                ('category', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=b'', max_length=100)),
                ('type', models.CharField(blank=True, default=b'', max_length=100)),
                ('acc', models.FloatField(blank=True, default=b'', max_length=5)),
                ('train', models.CharField(blank=True, default=b'', max_length=1)),
                ('config', models.CharField(blank=True, default=b'', max_length=1)),
                ('dir', models.CharField(blank=True, default=b'', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
