# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-19 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NNInfo',
            fields=[
                ('nn_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, default=b'', max_length=100)),
                ('type', models.CharField(blank=True, default=b'', max_length=100)),
                ('acc', models.CharField(blank=True, default=b'', max_length=5)),
                ('train', models.CharField(blank=True, default=b'', max_length=1)),
                ('config', models.CharField(blank=True, default=b'', max_length=1)),
                ('dir', models.CharField(blank=True, default=b'', max_length=200)),
                ('table', models.CharField(blank=True, default=b'', max_length=100)),
                ('query', models.CharField(blank=True, default=b'', max_length=5000)),
                ('datadesc', models.CharField(blank=True, default=b'', max_length=50000)),
                ('datasets', models.CharField(blank=True, default=b'', max_length=50000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
